# Generated by Django 4.1.7 on 2023-03-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
